spring:
  profiles:
    active: dev
  application:
    name: user_center
  datasource:
    #驱动类名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接的url
    url: jdbc:mysql://localhost:xxxx/xxxx
    #连接数据库的用户名
    username: root
    #连接数据库的密码
    password: xxxxxx
  #session 失效时间(分钟)
  session:
    timeout: 86400
  #redis配置
  data:
    redis:
      host: localhost
      port: xxxx
      password: xxxxxx
      database: 0

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: user_center.controller

mybatis-plus:
  configuration:
    #配置mybatis的日志, 指定输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启mybatis的驼峰命名自动映射开关 a_column ------> aCloumn
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值


